; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Fri May 10 2019 19:08:28 GMT-0700 (Pacific Daylight Time)

