; tpost3.g
; called after tool 3 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Fri May 10 2019 19:08:29 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P3

