; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Sun May 19 2019 18:51:30 GMT-0500 (CDT)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


